!obj:pylearn2.train.Train {
    # Here we specify the dataset to train on. We train on only the first 900 of the examples, so
    # that the rest may be used as a validation set.
    # The "&train" syntax lets us refer back to this object as "*train" elsewhere in the yaml file
    dataset: &train !obj:pylearn2.scripts.icml_2013_wrepl.black_box.black_box_dataset.BlackBoxDataset {
        which_set: 'train',
        start: 0,
        stop: 900,
        preprocessor: !obj:pylearn2.datasets.preprocessing.Standardize {},
        fit_preprocessor: 1,
        fit_preprocessor: 1,
    },
    # Here we specify the model to train as being an MLP
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 100,
        layers : [
            # We use two hidden layers with rectified linear activations
            !obj:pylearn2.models.maxout.Maxout {
                    layer_name: 'h0',
                    irange: .005,
                    num_units: 2000,
                    num_pieces: 5,
                    max_col_norm: 2.
            },
            !obj:pylearn2.models.maxout.Maxout {
                    layer_name: 'h1',
                    irange: .005,
                    num_units: 1000,
                    num_pieces: 8,
                    max_col_norm: 2.
            },
            !obj:pylearn2.models.maxout.Maxout {
                    layer_name: 'h2',
                    irange: .005,
                    num_units: 1000,
                    num_pieces: 8,
                    max_col_norm: 2.
            },
            !obj:pylearn2.models.maxout.Maxout {
                    layer_name: 'h3',
                    irange: .005,
                    num_units: 1000,
                    num_pieces: 8,
                    max_col_norm: 2.
            },
            !obj:pylearn2.models.mlp.Softmax {
                layer_name: 'y',
                init_bias_target_marginals: *train,
                # Initialize the weights to all 0s
                irange: .0,
                n_classes: 9
            }
        ],
        nvis: 1875,
    },
    # We train using SGD and momentum
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: 0.5,
        init_momentum: .5,
        # We monitor how well we're doing during training on a validation set
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:pylearn2.scripts.icml_2013_wrepl.black_box.black_box_dataset.BlackBoxDataset {
                    which_set: 'train',
                    start: 900,
                    stop: 1000,
                    preprocessor: !obj:pylearn2.datasets.preprocessing.Standardize {},
                    fit_preprocessor: 1,
                }
            },
       cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
            input_include_probs: { 'h0' : 1. },
            input_scales: { 'h0': 1. }
        },

        # We stop when validation set classification error hasn't decreased for 10 epochs
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 100
        },
    },
    # We save the model whenever we improve on the validation set classification error
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "best.pkl"
        },
        !obj:pylearn2.training_algorithms.sgd.MomentumAdjustor {
            start: 1,
            saturate: 250,
            final_momentum: .6
        },
        !obj:pylearn2.training_algorithms.sgd.LinearDecayOverEpoch {
            start: 1,
            saturate: 100,
            decay_factor: 0.01
        },
        !obj:noisy_encoder.utils.best_params.MonitorBasedBest {
            channel_name: 'valid_y_misclass',
            save_channel_names: ['valid_y_misclass'],
        }
    ],
    save_path: "last.pkl",
    save_freq: 100
}
