!obj:pylearn2.train.Train {
    dataset: &train  !obj:pylearn2.datasets.tfd.TFD {
        which_set: 'train',
        one_hot: 1,
        fold: %(fold)i,
        axes: ['c', 0, 1, 'b'],
        preprocessor: !obj:noisy_encoder.datasets.preprocessing.LeCunLCN {
            img_shape: [48, 48]
        }
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 128,
        layers: [
                 !obj:galatea.mlp.ConvLinearC01B {
                     layer_name: 'h0',
                     W_lr_scale: %(W_lr_scale_1)f,
                     b_lr_scale: %(b_lr_scale_1)f,
                     pad: 0,
                     detector_channels: %(num_channels_1)i,
                     channel_pool_size: 2,
                     kernel_shape: [8, 8],
                     pool_shape: [4, 4],
                     pool_stride: [2, 2],
                     irange: .005,
                     max_kernel_norm: .9,
                 },
                !obj:galatea.mlp.ConvLinearC01B {
                     layer_name: 'h1',
                     W_lr_scale: %(W_lr_scale_2)f,
                     b_lr_scale: %(b_lr_scale_2)f,
                     pad: 3,
                     detector_channels: %(num_channels_2)i,
                     channel_pool_size: 2,
                     kernel_shape: [8, 8],
                     pool_shape: [4, 4],
                     pool_stride: [2, 2],
                     irange: .005,
                     max_kernel_norm: 1.9365,
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     #max_col_norm: 3.873,
                     max_col_norm: 1.9365,
                     layer_name: 'y',
                     n_classes: 7,
                     irange: .005
                 }
                ],
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [48, 48],
            num_channels: 1,
            axes: ['c', 0, 1, 'b'],
        },
        dropout_include_probs: [ .5,.5, 1 ],
        dropout_input_include_prob: %(dropout_inp)f,
        dropout_input_scale: 1.,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: %(learning_rate)f,
        init_momentum: %(init_momentum)f,
        monitoring_dataset:
            {
                'valid': !obj:pylearn2.datasets.tfd.TFD {
                    which_set: 'valid',
                    one_hot: 1,
                    fold: %(fold)i,
                    axes: ['c', 0, 1, 'b'],
                    preprocessor: !obj:noisy_encoder.datasets.preprocessing.LeCunLCN {
                        img_shape: [48, 48]
                    }
                },
                'test': !obj:pylearn2.datasets.tfd.TFD {
                    which_set: 'test',
                    one_hot: 1,
                    fold: %(fold)i,
                    axes: ['c', 0, 1, 'b'],
                    preprocessor: !obj:noisy_encoder.datasets.preprocessing.LeCunLCN {
                        img_shape: [48, 48]
                    }
                },
            },
        cost: !obj:pylearn2.costs.cost.MethodCost {
                method: 'cost_from_X',
                supervised: 1
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 100
        },
        update_callbacks: !obj:pylearn2.training_algorithms.sgd.ExponentialDecay {
            decay_factor: %(exp_decay)f,
            min_lr: %(exp_dc_min)f
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "%(save_path)s_best.pkl"
        },
        !obj:pylearn2.training_algorithms.sgd.MomentumAdjustor {
            start: %(momentum_start)i,
            saturate: %(momentum_saturate)i,
            final_momentum: %(final_momentum)f
        }
    ],
    save_path: "%(save_path)s_last.pkl",
    save_freq: 1
}


