!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.sandbox.nlp.datasets.penntree.PennTreebank {
        which_set: 'train',
        context_len: &context_len 7,
    },
    model: !obj:noisylearn.projects.gating2.vLBL_NCE {
        batch_size: &batch_size 100,
        noise_p: !pkl: '${PYLEARN2_DATA_PATH}/PennTreebankCorpus/penntree_unigram.npy',
        dict_size: 10000,
        dim: 100,
        context_length: *context_len,
        k: 10,
        irange: 0.0780113956074,
        #max_col_norm: 3.609955,
        #c_max_col_norm: 3.609955,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: *batch_size,
        train_iteration_mode: 'even_shuffled_sequential',
        monitor_iteration_mode: 'even_shuffled_sequential',
        learning_rate: 0.0151577,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5,
        },
        monitoring_dataset:
            {
                #'train' : *train,
                'valid' : !obj:pylearn2.sandbox.nlp.datasets.penntree.PennTreebank {
                        which_set: 'valid',
                        context_len: *context_len
                },
                'test' : !obj:pylearn2.sandbox.nlp.datasets.penntree.PennTreebank {
                        which_set: 'test',
                        context_len: *context_len
                },
            },
        #cost: !obj:noisylearn.projects.gating2.cost.NCE {}
        cost: !obj:pylearn2.costs.mlp.Default {},
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_perplexity",
            prop_decrease: 0.,
            N: 100
        },
        #termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
            #max_epochs: 1
        #},
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_perplexity',
             save_path: "/data/lisatmp2/mirzamom/results/nce/TwMkGNl_best.pkl"
        },
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 154,
            final_momentum: 0.731861
        },
        !obj:pylearn2.training_algorithms.sgd.LinearDecayOverEpoch {
            start: 1,
            saturate: 150,
            decay_factor: 0.007179,
        },
    ],
    save_path: "/data/lisatmp2/mirzamom/results/nce/TwMkGNl_.pkl",
    save_freq: 1
}
